repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      # - id: tflint
      - id: shellcheck
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0 
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: terragrunt_fmt
  # - repo: git://github.com/marshall7m/pre-commit-terraform
  #   rev: v0.0.2
  #   hooks:
  #     - id: terraform_tests
  # - repo: meta
  #   hooks:
  #     - id: identity
  #       files: >
  #           (?x)(
  #               .+\.m$
  #           )
  #       args:
  #         - --argument
  #         - 'value'