version: 0.2
env:
  shell: bash
phases:
  pre_build:
      commands:
        - aws configure set preview.sdb true
        - pr_id=$(echo $CODEBUILD_SOURCE_VERSION | cut -d "/" -f 2)
        - "echo Pull Request ID: ${pr_id}"
        - base_ref=$(echo $CODEBUILD_WEBHOOK_BASE_REF | cut -d "/" -f 3)
        - "echo Base Ref: ${base_ref}"
        - head_ref=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d "/" -f 3)
        - "echo Head Ref: ${head_ref}"
        - "echo Build Number: ${CODEBUILD_BUILD_NUMBER}"
        - "echo Queue DB: ${DOMAIN_NAME}"
      on-failure: ABORT
  build:
    commands:
      - |
        attr=$( jq -n \
          --arg base_ref "$base_ref" \
          --arg head_ref "$head_ref" \
          --arg pr_id "$pr_id" \
          '[{Name: "BaseRef", Value: $base_ref, Replace: true}, {Name: "HeadRef", Value: $head_ref, Replace: true}]' )
        echo Record Attributes: $attr
      
        aws sdb put-attributes \
          --domain-name ${DOMAIN_NAME} \
          --item-name ${pr_id} \
          --attributes "$attr" 