version: 0.2
phases:
  build:
    commands:
      - pr_id=$(echo $CODEBUILD_SOURCE_VERSION | cut -d "/" -f 2)
      - base_ref=$(echo $CODEBUILD_WEBHOOK_BASE_REF | cut -d "/" -f 3)
      - head_ref=$(echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d "/" -f 3)
      - |
        record=$( jq -n \
          --arg pr_id "$pr_id" \
          --arg base_ref "$base_ref" \
          --arg head_ref "$head_ref" \
          --arg build_num "$CODEBUILD_BUILD_NUMBER" \
          '{PullRequestID: {N: $pr_id}, BaseRef: {S: $base_ref}, HeadRef: {S: $head_ref}, BuildNumber: {N: $build_num}}' )
      - echo $record
      - |
        response=$(aws dynamodb put-item \
          --table-name mut-infrastructure-ci-pr-queue \
          --item "$record" \
          --condition-expression "attribute_not_exists(PullRequestID)" 2>&1)

        exception=".+\(ConditionalCheckFailedException\).+"
        if [[ $response =~ $exception ]]; 
            then 
                echo "Pull Request already in queue" 
            else 
                echo "$response"
        fi

