version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      - next_pr=$(aws sdb select --select-expression "SELECT * FROM `$DOMAIN_NAME`" --max-items 1 | jq '.Items[0]')
      - pr_id=$(echo $next_pr | jq '.Name')
      - head_ref=$(echo $next_pr | jq '.Attributes | .[] | select(.Name=="HeadRef") | .Value')
      - git fetch origin pull/$pr_id/head:$head_ref
      - git checkout $head_ref
      - python /opt/testing/scripts/tg_dep_order.py --machine-arn $STEP_MACHINE_ARN
      - aws sdb delete-attributes --item-name $pr_id --domain-name $DOMAIN_NAME