version: 0.2
env:
  shell: bash
phases:
  build:
    commands:
      - git fetch origin pull/$PR_ID/head:$HEAD_REF
      - git checkout $HEAD_REF
      - terragrunt $COMMAND --terragrunt-working-dir $PATH $EXTRA_ARGS