version: "3.8"
services:
  postgres:
    image: postgres:10.18-alpine
    volumes:
      - "$PWD/docker-pgsql-entrypoint:/docker-entrypoint-initdb.d"
      - "$PWD/docker-pgsql-volume:/var/lib/postgresql/data" 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - TESTING_POSTGRES_USER
      - TESTING_POSTGRES_DB
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5000s
      retries: 50
  testing:
    build:
      context: ./testing-img
    container_name: metadb
    image: bats-testing:${TAG}
    volumes:
      - "$PWD:/src"
    environment:
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGHOST
    command: ["/bin/bash"]
    depends_on: 
      - postgres
    