version: "3.8"
services:
  postgres:
    image: postgres:10.14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testing_password
      - TESTING_POSTGRES_USER=testing_user
      - TESTING_POSTGRES_DB=testing_metadb
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 5000s
      retries: 50
  testing:
    stdin_open: true
    tty: true
    image: ghcr.io/marshall7m/terrace:v0.1.2
    volumes:
      - "$PWD:/src"
    environment:
      - PGUSER
      - PGPASSWORD
      - PGDATABASE
      - PGHOST
      - PGPORT
      - ADDITIONAL_PATH
    command: ["/bin/bash"]