version: '3.8'
services:
  postgres:
    image: postgres:10.14-alpine
    restart: always
    container_name: postgres
    volumes:
    - $PWD/docker-pgsql-entrypoint:/docker-entrypoint-initdb.d
    - $PWD/docker-pgsql-volume:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 15s
      timeout: 5000s
      retries: 50
    profiles: [unit, integration]

  sf-local:
    image: amazon/aws-stepfunctions-local:1.10.2
    container_name: step-function-local
    volumes:
    - $PWD/tests/integration/step-function/mock_sf_cfg.json:/src/mock_sf_cfg.json
    ports:
    - 8083:8083
    environment:
    - SFN_MOCK_CONFIG=/src/mock_sf_cfg.json
    profiles: [integration]

  local-data-api:
    # using latest img until pinned version fixes issue: https://github.com/koxudaxi/local-data-api/issues/217
    image: koxudaxi/local-data-api:latest
    restart: always
    environment:
    - ENGINE=PostgresSQL
    - POSTGRES_HOST=postgres
    - POSTGRES_PORT=5432
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - CLUSTER_ARN=arn:aws:rds:us-west-2:123456789012:cluster:${TF_VAR_mut_id}-cluster
    - SECRET_ARN=arn:aws:secretsmanager:us-west-2:123456789012:secret:${TF_VAR_mut_id}-data-api-${TF_VAR_metadb_username}-credentials
    ports:
    - 8080:80
    profiles: [unit, integration]

  localstack:
    image: localstack/localstack:1.0.4
    environment:
    - LAMBDA_EXECUTOR=docker_reuse
    - DOCKER_HOST=unix:///var/run/docker.sock
    - DEFAULT_REGION=us-west-2
    - DEBUG=1
    - DATA_DIR=/tmp/localstack/data
    - PORT_WEB_UI=8080
    ports:
    - 127.0.0.1:4566:4566
    - 127.0.0.1:4510-4559:4510-4559
    - 8079:8080
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/localstack:/tmp/localstack/data

  moto:
    image: motoserver/moto:4.0.1
    ports:
    - 5000:5000
    profiles: [integration]
  unit:
    network_mode: host
    stdin_open: true
    tty: true
    image: terraform-aws-infrastructure-live/unit
    build: ./tests/unit
    volumes:
    - $PWD:/src
    environment:
    - AWS_ACCESS_KEY_ID=mock-aws-access-key
    - AWS_SECRET_ACCESS_KEY=mock-aws-secret-key
    - AWS_REGION=us-east-1
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_SESSION_TOKEN=mock-aws-session-token
    - AWS_SESSION_EXPIRATION=mock-aws-exp
    - TF_VAR_testing_unit_github_token
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGDATABASE=postgres
    - PGHOST=postgres
    - PGPORT=5432
    - AURORA_CLUSTER_ARN=arn:aws:rds:us-west-2:123456789012:cluster:${TF_VAR_mut_id}-cluster
    - AURORA_SECRET_ARN=arn:aws:secretsmanager:us-west-2:123456789012:secret:${TF_VAR_mut_id}-data-api-${TF_VAR_metadb_username}-credentials
    - METADB_NAME=${METADB_NAME}
    - METADB_LOCAL_ENDPOINT=http://127.0.0.1:8080
    entrypoint: [/bin/bash, entrypoint.sh]
    profiles: [unit]
    depends_on:
    - local-data-api
    - postgres

  integration:
    network_mode: host
    stdin_open: true
    tty: true
    image: terraform-aws-infrastructure-live/integration
    build: ./tests/integration
    volumes:
    - $PWD:/src
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - AWS_ACCESS_KEY_ID=dummy-key
    - AWS_SECRET_ACCESS_KEY=dummy-secret
    - AWS_REGION=us-west-2
    - AWS_DEFAULT_REGION=us-west-2
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGDATABASE=postgres
    - PGHOST=postgres
    - PGPORT=5432
    - TF_VAR_mut_id
    - TF_VAR_metadb_username
    entrypoint: [/bin/bash, entrypoint.sh]
    profiles: [integration]
    depends_on:
    - postgres
    - sf-local
    - local-data-api
    - moto
    - localstack

  e2e:
    stdin_open: true
    tty: true
    image: ghcr.io/marshall7m/terrace:v0.1.11
    volumes:
    - $PWD:/src
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - AWS_DEFAULT_REGION
    - AWS_SESSION_TOKEN
    - AWS_SESSION_EXPIRATION
    - TF_VAR_testing_integration_github_token
    - TF_VAR_registry_password
    - TF_VAR_github_token_ssm_value
    - TF_VAR_approval_request_sender_email
    - UNTIL_AWS_EXP=1h
    - ADDITIONAL_PATH
    entrypoint: [/bin/bash, entrypoint.sh]
