# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">=0.15.0"
  required_providers {


    testing = {
      source  = "apparentlymart/testing"
      version = "0.0.2"
    }
  }
}
provider "testing" {}


