CREATE USER :'CI_USER' WITH PASSWORD :'CI_PASSWORD';
GRANT :'PGUSER' TO :'CI_USER';

GRANT CONNECT, TEMPORARY ON DATABASE :'PGDATABASE' TO :'CI_USER';
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA :'PG_SCHEMA' TO :'CI_USER';
GRANT USAGE ON SCHEMA :'PG_SCHEMA' TO :'CI_USER';
GRANT SELECT, INSERT, UPDATE, REFERENCES, TRIGGER ON executions IN SCHEMA :'PG_SCHEMA' TO :'CI_USER';
GRANT SELECT ON account_dim IN SCHEMA :'PG_SCHEMA' TO :'CI_USER';

SET ROLE :'CI_USER';

-- set default schema for user
ALTER ROLE :'CI_USER' SET search_path TO :'PG_SCHEMA';