name: Publish Docker image

on:
  release:
    types: [published]
    paths:
      - buildspecs/img/**
  push:
    branches:
      - master
    tags:
      - ci
      - tests
    paths:
      - buildspecs/img/**

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker release image
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'release' }}
        with:
          context: "{{defaultContext}}:buildspecs/img"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
      
      - name: Build and push Docker master image
        uses: docker/build-push-action@v3
        if: ${{ github.event_name == 'push' }}
        with:
          context: "{{defaultContext}}:buildspecs/img"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.event.push.head_commit.id }}