name: Publish Docker image

on:
  push:
    branches:
    - master
    tags:
    - ci
    - tests
    paths:
    - docker/**
    - functions/webhook_receiver/**
    - .github/workflows/build.yml

  release:
    types: [published]
    paths:
    - docker/**
    - functions/webhook_receiver/**
    - .github/workflows/build.yml

jobs:
  ecs_task:
    name: Push ECS task Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: |
          docker/**

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker master image
      uses: docker/build-push-action@v3
      if: ${{ (github.event_name == 'push') && (steps.changed-files.outputs.any_changed == 'true') }}
      with:
        context: docker
        push: true
        tags: |-
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Build and push Docker release image
      uses: docker/build-push-action@v3
      if: ${{ github.event_name == 'release' }}
      with:
        context: docker
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/tasks:${{ github.event.release.tag_name }}

  receiver:
    name: Push Lambda Receiver Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: |
          functions/webhook_receiver/**

    - name: Log into GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker master image
      uses: docker/build-push-action@v3
      if: ${{ (github.event_name == 'push') && (steps.changed-files.outputs.any_changed == 'true') }}
      with:
        context: functions/webhook_receiver
        push: true
        tags: |-
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Build and push Docker release image
      uses: docker/build-push-action@v3
      if: ${{ github.event_name == 'release' }}
      with:
        context: functions/webhook_receiver
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/tasks:${{ github.event.release.tag_name }}
