name: "Release"
on:
  release:
    types: [published]

jobs:
  auto-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Update source_version.txt
        id: source_version
        shell: bash
        if: ${{ !env.ACT }}
        run: |
          echo ${{ github.event.release.tag_name }} > source_version.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ !env.ACT }}
        with:
          commit_message: Auto update source_version.txt