name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
    tags:
    - ci
    - tests
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md
    - docker/**
    - .github/workflows/build.yml

  push:
    branches:
    - master
    tags:
    - ci
    - tests
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md
    - docker/**
    - .github/workflows/build.yml

env:
  PYTEST_ADDOPTS: --color=yes
  PYTHON_VERSION: pypy-3.9
  AWS_REGION: us-west-2
  AWS_DEFAULT_REGION: us-west-2
jobs:
  precommit:
    runs-on: ubuntu-latest
    container: ghcr.io/marshall7m/terrace:v0.1.13
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref || github.ref }}

    - name: Hooks
      shell: bash
      run: |
        source $VIRTUAL_ENV/bin/activate
        python3 -m pip install -e ".[precommit]"
        pre-commit install
        pre-commit run --all-files

    - name: Update README.md TOC
      id: readme_toc
      shell: bash
      if: ${{ !env.ACT }}
      run: gh-md-toc --no-backup README.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ !env.ACT }}
      with:
        commit_message: Auto update markdown TOC

  unit:
    needs: precommit
    runs-on: ubuntu-latest
    env:
      TF_VAR_testing_unit_github_token: ${{ secrets.TF_VAR_TESTING_UNIT_GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: mask sensitive
      run: |
        echo "::add-mask::$TF_VAR_testing_unit_github_token"

    - name: Configure AWS Credentials for remote workflow
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Tests
      id: act_pytest_unit
      shell: bash
      run: |
        docker compose run unit pytest -vv tests/unit

  integration:
    # needs: [precommit, unit]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Tests
      id: act_pytest_integration
      shell: bash
      run: |
        docker compose run --rm integration pytest -vv tests/integration/tasks

  e2e:
    needs: [precommit, unit]
    runs-on: ubuntu-latest
    container: ghcr.io/marshall7m/terrace:v0.1.13
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_testing_integration_github_token: ${{ secrets.TF_VAR_TESTING_INTEGRATION_GITHUB_TOKEN }}
      TF_VAR_registry_password: ${{ secrets.TF_VAR_TESTING_INTEGRATION_GITHUB_TOKEN }}
      TF_VAR_github_token_ssm_value: ${{ secrets.TF_VAR_GITHUB_TOKEN_SSM_VALUE }}
      TF_VAR_approval_request_sender_email: ${{ secrets.TF_VAR_APPROVAL_REQUEST_SENDER_EMAIL }}
    steps:
    - uses: actions/checkout@v3
    - name: mask sensitive
      run: |
        echo "::add-mask::$TF_VAR_testing_integration_github_token"
        echo "::add-mask::$TF_VAR_registry_password"
        echo "::add-mask::$TF_VAR_github_token_ssm_value"
        echo "::add-mask::$TF_VAR_approval_request_sender_email"

    - name: Configure AWS Credentials for remote workflow
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ !env.ACT }}
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 21600   # 6hrs

    - name: Configure AWS Credentials for local workflow
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ env.ACT }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Docker
      id: unit_install_docker
      shell: bash
      run: |
        bash ./runner_install_docker.sh

    - name: Tests
      id: pytest_integration
      shell: bash
      run: |-
        source $VIRTUAL_ENV/bin/activate
        python3 -m pip install -e ".[integration]"
        pytest -vv tests/e2e
