name: Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
    - master
    tags:
    - ci
    - tests
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md
    - docker/**
    - .github/workflows/build.yml

  push:
    branches:
    - master
    tags:
    - ci
    - tests
    paths-ignore:
    - .gitignore
    - LICENSE.md
    - README.md
    - docker/**
    - .github/workflows/build.yml

env:
  PYTEST_ADDOPTS: --color=yes
  PYTHON_VERSION: pypy-3.9
  AWS_REGION: us-west-2
  AWS_DEFAULT_REGION: us-west-2
  DEV_DOCKER_IMG: dev
jobs:
  precommit:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Hooks
      shell: bash
      run: docker compose -f ./.devcontainer/docker-compose.yml run dev pre-commit run -a

    - name: Update README.md TOC
      id: readme_toc
      shell: bash
      if: ${{ !env.ACT }}
      run: gh-md-toc --no-backup README.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      if: ${{ !env.ACT }}
      with:
        commit_message: Auto update markdown TOC

  unit:
    needs: precommit
    runs-on: ubuntu-latest
    env:
      TF_VAR_testing_github_token: ${{ secrets.TF_VAR_TESTING_GITHUB_TOKEN }}
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3

    - name: mask sensitive
      run: echo "::add-mask::$TF_VAR_testing_github_token"

    - name: Tests
      shell: bash
      run: docker compose -f ./.devcontainer/docker-compose.yml run dev pytest -vv tests/unit

  integration:
    needs: [precommit, unit]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Deps
      shell: bash
      run: python3 -m pip install -e .

    - name: Tests
      shell: bash
      run: docker compose -f ./.devcontainer/docker-compose.yml run dev pytest -vv tests/integration

  e2e:
    needs: [precommit, unit, integration]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_testing_github_token: ${{ secrets.TF_VAR_TESTING_GITHUB_TOKEN }}
      TF_VAR_registry_password: ${{ secrets.TF_VAR_TESTING_GITHUB_TOKEN }}
      TF_VAR_github_token_ssm_value: ${{ secrets.TF_VAR_GITHUB_TOKEN_SSM_VALUE }}
      TF_VAR_approval_request_sender_email: ${{ secrets.TF_VAR_APPROVAL_REQUEST_SENDER_EMAIL }}
    steps:
    - uses: actions/checkout@v3

    - name: mask sensitive
      run: |
        echo "::add-mask::$TF_VAR_testing_github_token"
        echo "::add-mask::$TF_VAR_registry_password"
        echo "::add-mask::$TF_VAR_github_token_ssm_value"
        echo "::add-mask::$TF_VAR_approval_request_sender_email"

    - name: Configure AWS Credentials for remote workflow
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ !env.ACT }}
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-duration-seconds: 21600   # 6hrs

    - name: Configure AWS Credentials for local workflow
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ env.ACT }}
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Tests
      shell: bash
      run: docker compose -f ./.devcontainer/docker-compose.yml run dev pytest -vv tests/e2e
